title = "Gitleaks config"
# Define rules for what Gitleaks should search for.
# This is a basic configuration.
[[rules]]
    description = "AWS Manager ID"
    regex = 'A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA'
    tags = ["key", "AWS"]